package mending;
import java.nio.file.*;
import net.fabricmc.api.ModInitializer;
import net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.item.*;
import net.minecraft.world.level.GameType;
import net.minecraft.core.component.DataComponents;
import net.minecraft.core.registries.Registries;
import net.minecraft.world.item.enchantment.*;
import me.pajic.simple_smithing_overhaul.items.ModItems;
import me.pajic.simple_smithing_overhaul.util.ModDataComponents;
import me.pajic.simple_smithing_overhaul.SSO;
public class MendingServerQa implements ModInitializer {
 final Path control=Path.of(System.getProperty("mending.qa.control"));
 final String[] cases={"mending","matching-three","no-crouch","no-material","no-mending","incompatible","skip-incompatible","repeated","broken-pick","bow","broken-bow","cooldown"};
 public static int usePackets; int scenario,ticks;boolean waiting,done;ItemStack original;
 void write(String file,String text)throws Exception{Files.writeString(control.resolve(file),text);}
 void log(String text)throws Exception{Files.writeString(control.resolve("server-evidence.txt"),text+"\n",StandardOpenOption.CREATE,StandardOpenOption.APPEND);}
 void check(boolean ok,String s){if(!ok)throw new AssertionError(s);}
 ItemStack stone(ServerPlayer p,boolean match,boolean triple){var stone=new ItemStack(ModItems.WHETSTONE);var e=new ItemEnchantments.Mutable(ItemEnchantments.EMPTY);var reg=p.registryAccess().lookupOrThrow(Registries.ENCHANTMENT);if(match)e.set(reg.getOrThrow(Enchantments.MENDING),1);if(triple){e.set(reg.getOrThrow(Enchantments.EFFICIENCY),1);e.set(reg.getOrThrow(Enchantments.UNBREAKING),1);}stone.set(DataComponents.STORED_ENCHANTMENTS,e.toImmutable());return stone;}
 public void onInitialize(){ServerTickEvents.END_SERVER_TICK.register(server->{if(done||server.getPlayerList().getPlayers().isEmpty())return;try{var p=server.getPlayerList().getPlayers().getFirst();if(++ticks<40)return;
 if(waiting){if(ticks>600)throw new AssertionError("timeout "+cases[scenario]);if(!Files.exists(control.resolve("ack"))||!Files.readString(control.resolve("ack")).equals(cases[scenario]))return;var tool=p.getInventory().getItem(0);var stone=p.getInventory().getItem(1);int materials=p.getInventory().getItem(2).getCount();int repairs=tool.getOrDefault(ModDataComponents.REPAIR_COUNT,0);boolean negative=scenario>=2&&scenario<=5||scenario==11;int expected=negative?0:scenario==7?3:!Boolean.getBoolean("mending.isolate-broken")&&(scenario==8||scenario==10)?2:1;int expectedCount=Boolean.getBoolean("mending.original-only")?0:expected;int expectedDamage=Math.max(0,original.getDamageValue()-expected*((tool.getMaxDamage()+me.pajic.simple_smithing_overhaul.util.ModUtil.determineUnitCost(tool)-1)/me.pajic.simple_smithing_overhaul.util.ModUtil.determineUnitCost(tool)));int expectedMaterials=(scenario==3?0:64)-expected;boolean observed=repairs==expectedCount&&tool.getDamageValue()==expectedDamage&&materials==expectedMaterials;log("CASE "+cases[scenario]+" usePackets="+usePackets+" expectedDamage="+expectedDamage+" expectedMaterials="+expectedMaterials+" expectedUses="+expected+" expectedRepairs="+expectedCount+" observedRepairs="+repairs+" initialDamage="+original.getDamageValue()+" damage="+tool.getDamageValue()+" materials="+materials+" stoneDamage="+stone.getDamageValue()+" laterStoneDamage="+p.getInventory().getItem(3).getDamageValue()+" enchantsPreserved="+tool.getEnchantments().equals(original.getEnchantments())+" shift="+p.isShiftKeyDown()+" expectedBehavior="+observed);check(tool.getEnchantments().equals(original.getEnchantments()),"enchants changed");write("snapshot",tool.getDamageValue()+":"+materials+":"+repairs+":"+stone.getDamageValue());write("snapshot-case",cases[scenario]);waiting=false;scenario++;if(Boolean.getBoolean("mending.isolate-broken")){if(scenario==1)scenario=8;else if(scenario==9)scenario=10;else if(scenario==11)scenario=12;}ticks=0;return;}
 if(Files.exists(control.resolve("snapshot-case"))&&!Files.exists(control.resolve("checked")))return;
 if(scenario==cases.length){write("result.txt","PASS fixture completed (not an all-cases behavior verdict): "+(Boolean.getBoolean("mending.isolate-broken")?3:cases.length)+" native use observations; inspect per-case expectedBehavior (known defects may be false)\n");done=true;return;}
 if(Boolean.getBoolean("mending.isolate-broken"))SSO.CONFIG.mendingRework.autoRepairOnBreak.accept(false);usePackets=0;p.closeContainer();p.getInventory().clearContent();p.setGameMode(GameType.SURVIVAL);p.setPermanentlyInvulnerable(true);p.getInventory().setSelectedSlot(0);p.getCooldowns().removeCooldown(net.minecraft.resources.Identifier.parse("minecraft:diamond_pickaxe"));
 var tool=new ItemStack(scenario==9||scenario==10?Items.BOW:Items.DIAMOND_PICKAXE);tool.setDamageValue(scenario==8||scenario==10?tool.getMaxDamage():scenario==7?1560:Math.min(780,tool.getMaxDamage()-1));var reg=p.registryAccess().lookupOrThrow(Registries.ENCHANTMENT);if(scenario!=4)tool.enchant(reg.getOrThrow(Enchantments.MENDING),1);if(scenario==1||scenario==6){tool.enchant(reg.getOrThrow(Enchantments.EFFICIENCY),1);tool.enchant(reg.getOrThrow(Enchantments.UNBREAKING),1);}if(scenario==8||scenario==10)tool.set(ModDataComponents.BROKEN,true);original=tool.copy();p.getInventory().setItem(0,tool);p.getInventory().setItem(1,stone(p,scenario!=5&&scenario!=6,scenario==1));if(scenario!=3)p.getInventory().setItem(2,new ItemStack(scenario==9||scenario==10?Items.STRING:Items.DIAMOND,64));if(scenario==6)p.getInventory().setItem(3,stone(p,true,true));if(scenario==11)p.getCooldowns().addCooldown(tool,200);p.inventoryMenu.broadcastFullState();Files.deleteIfExists(control.resolve("checked"));log("CONFIG "+cases[scenario]+" broken="+me.pajic.simple_smithing_overhaul.util.ModUtil.isBroken(tool)+" enabled="+SSO.CONFIG.mendingRework.enabled.get()+" shift="+SSO.CONFIG.mendingRework.repairOnShiftUse.get());write("command",cases[scenario]);waiting=true;ticks=0;
 }catch(Throwable failure){done=true;failure.printStackTrace();try{write("result.txt","FAIL server "+failure);}catch(Exception ignored){}}});}
}
